### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by dylanaraps** [dylanaraps/dylanaraps.github.io#1]
**General**

- [x] Rewrite the `build` script properly.
    - It's hacked together right now.
    - [x] Un-hardcode page names.
- [x] Write usage docs.
    - [x] Dependencies
    - [x] Python local server
        - `python3 -m http.server`
- [x] Add a favicon.
- [x] Create a script or find a program to watch `*.md` files.
    - `gulp` or `grunt` seem overkill here.

**Rice**

- [x] Add wallpaper links to posts.
- [x] Make summary screenshots smaller.

**GitHub CSS**

- [x] Minify CSS.
    - This can be done in the `build` script.
- [x] Add link back to original repo.
- [x] Thank original project in README.

**HTML**

- [x] Better `sed` commands to minify `html`.
